### ISSUE TITLE
Still cant play a clean vanilla ultimate after using UMM

### ISSUE THREAD

**Issue by KamiSquadX** [ultimate-research/UltimateModManager#8] opened 2019-12-17 02:32 UTC
I have to note that two accounts share ultimate and each account has their own mods it seems. Playing wifi on one account works flawlessly as i can tell. But on the main account certain characters shut the whole arena down. Like Ganon, ZSS, Daisy, Peach, Rob, for example.

How can we just install a clean ultimate w.o any mods?

**Comment by MegaSuperab** [comment] 2019-12-18 00:09
The real problem is you're leaving yourself wide open to a ban risk by using mods online.

**Comment by Genwald** [comment] 2019-12-18 23:42
Duplicate of #7

**Closed by Genwald** 2019-12-18 23:42 UTC
